### ISSUE TITLE
Example files

### ISSUE THREAD

**Issue by HTSpecOps** [nemart69/sh1107-micropython#2]
Hi,

Would it be possible to upload an example file for this drivers usage ?

thx

**Comment by nemart69** [comment]
I am sorry but I do not have a simple example to upload, I would have to create one and test it a bit on some hardware. In any case, you can get inspired by examples for I2C-based SSD1306 driver in the official Micropython documentation: https://docs.micropython.org/en/latest/esp8266/tutorial/ssd1306.html. Just replace _ssd1306_ with _sh1107_ and _SSD1306_I2C_ with _SH1107_I2C_. The API is the same, most of the methods are inherited from framebuf.FrameBuffer.

**Comment by HTSpecOps** [comment]
ok thanks ! If I have time I will make one and do a PR
