### ISSUE TITLE
clearing the display

### ISSUE THREAD

**Issue by williamjball** [nemart69/sh1107-micropython#4]
This is working well for me except I don't know how to clear the display completely and reset for addition input.

**Comment by nemart69** [comment]
fill() can be used for this.

`disp = sh1107.SH1107_I2C(128, 64, ...)`
`...`
`disp.fill(0)`

This method is inherited from framebuf: https://docs.micropython.org/en/latest/library/framebuf.html#

**Comment by williamjball** [comment]
Thanks for the email. Using fill() from framebuf did the job.
